In [86]:
from collections import Counter

In [87]:
a=!ls

In [88]:
a

['project.ipynb', 'sample_submission.csv', 'test.csv', 'train.csv']

In [89]:
test=pd.read_csv(a[2])
train=pd.read_csv(a[3])

In [157]:
train.columns=['date', 'day', 'total', 'vacation', 'away', 'extra', 'home', 'morning', 'lunch', 'dinner', 'lun_n', 'din_n']
train.head()

date day  total  vacation  away  extra  home  \
0  2016-02-01   월   2601        50   150    238   0.0   
1  2016-02-02   화   2601        50   173    319   0.0   
2  2016-02-03   수   2601        56   180    111   0.0   
3  2016-02-04   목   2601       104   220    355   0.0   
4  2016-02-05   금   2601       278   181     34   0.0   

                                             morning  \
0  모닝롤/찐빵  우유/두유/주스 계란후라이  호두죽/쌀밥 (쌀:국내산) 된장찌개  쥐...   
1  모닝롤/단호박샌드  우유/두유/주스 계란후라이  팥죽/쌀밥 (쌀:국내산) 호박젓국찌...   
2  모닝롤/베이글  우유/두유/주스 계란후라이  표고버섯죽/쌀밥 (쌀:국내산) 콩나물국...   
3  모닝롤/토마토샌드  우유/두유/주스 계란후라이  닭죽/쌀밥 (쌀,닭:국내산) 근대국...   
4  모닝롤/와플  우유/두유/주스 계란후라이  쇠고기죽/쌀밥 (쌀:국내산) 재첩국  방...   

                                               lunch  \
0  쌀밥/잡곡밥 (쌀,현미흑미:국내산) 오징어찌개  쇠불고기 (쇠고기:호주산) 계란찜 ...   
1  쌀밥/잡곡밥 (쌀,현미흑미:국내산) 김치찌개  가자미튀김  모둠소세지구이  마늘쫑무...   
2  카레덮밥 (쌀,현미흑미:국내산) 팽이장국  치킨핑거 (닭고기:국내산) 쫄면야채무침 ...   
3  쌀밥/잡곡밥 (쌀,현미흑미:국내산) 쇠고기무국  주꾸미볶음  부추전  시금치나물  ...   
4  쌀밥/잡곡밥 (쌀,현미흑미:국내산) 떡국  돈육씨앗강정 (돼지고기:국내산) 우엉잡채...   

                                              dinner   lun_n  din_n  
0  쌀밥/잡곡밥 (쌀,현미흑미:국내산) 육개장  자반고등어구이  두부조림  건파래무침 ...  1039.0  331.0  
1  콩나물밥*양념장 (쌀,현미흑미:국내산) 어묵국  유산슬 (쇠고기:호주산) 아삭고추무...   867.0  560.0  
2  쌀밥/잡곡밥 (쌀,현미흑미:국내산) 청국장찌개  황태양념구이 (황태:러시아산) 고기...  1017.0  573.0  
3  미니김밥*겨자장 (쌀,현미흑미:국내산) 우동  멕시칸샐러드  군고구마  무피클  포...   978.0  525.0  
4  쌀밥/잡곡밥 (쌀,현미흑미:국내산) 차돌박이찌개 (쇠고기:호주산) 닭갈비 (닭고기:...   925.0  330.0

In [225]:
train.replace(value=' ',regex=r':\(.*\)|\s-\s.',inplace=True)
train

date day  total  vacation  away  extra   home  \
0     2016-02-01   월   2601        50   150    238    0.0   
1     2016-02-02   화   2601        50   173    319    0.0   
2     2016-02-03   수   2601        56   180    111    0.0   
3     2016-02-04   목   2601       104   220    355    0.0   
4     2016-02-05   금   2601       278   181     34    0.0   
...          ...  ..    ...       ...   ...    ...    ...   
1200  2021-01-20   수   2983        75   198      4  391.0   
1201  2021-01-21   목   2983        92   231    462  351.0   
1202  2021-01-22   금   2983       255   248      1  303.0   
1203  2021-01-25   월   2983       107   153    616  327.0   
1204  2021-01-26   화   2983        69   183    551  362.0   

                                                morning  \
0     모닝롤 찐빵  우유 두유 주스 계란후라이  호두죽 쌀밥 (쌀:국내산) 된장찌개  쥐...   
1     모닝롤 단호박샌드  우유 두유 주스 계란후라이  팥죽 쌀밥 (쌀:국내산) 호박젓국찌...   
2     모닝롤 베이글  우유 두유 주스 계란후라이  표고버섯죽 쌀밥 (쌀:국내산) 콩나물국...   
3     모닝롤 토마토샌드  우유 두유 주스 계란후라이  닭죽 쌀밥 (쌀,닭:국내산) 근대국...   
4     모닝롤 와플  우유 두유 주스 계란후라이  쇠고기죽 쌀밥 (쌀:국내산) 재첩국  방...   
...                                                 ...   
1200  모닝롤 페퍼로니피자 우유 주스 계란후라이 찐계란 크루통크림스프 흑미밥 아귀지리 마늘...   
1201  모닝롤 생크림단팥빵 우유 주스 계란후라이 찐계란 누룽지탕 흑미밥 떡국 해물땡굴소스볶...   
1202  모닝롤 BLT샌드위치 우유 주스 계란후라이 찐계란 흑임자죽 흑미밥 바지락살국 두부조...   
1203  모닝롤 호박고구마오븐구이 우유 주스 계란후라이 찐계란 누룽지탕 흑미밥 감자양파국 분...   
1204  모닝롤 야채샌드 우유 주스 계란후라이 찐계란 참치죽 흑미밥 홍합탕 애호박새우젓볶음 ...   

                                                  lunch  \
0     쌀밥 잡곡밥 (쌀,현미흑미:국내산) 오징어찌개  쇠불고기 (쇠고기:호주산) 계란찜 ...   
1     쌀밥 잡곡밥 (쌀,현미흑미:국내산) 김치찌개  가자미튀김  모둠소세지구이  마늘쫑무...   
2     카레덮밥 (쌀,현미흑미:국내산) 팽이장국  치킨핑거 (닭고기:국내산) 쫄면야채무침 ...   
3     쌀밥 잡곡밥 (쌀,현미흑미:국내산) 쇠고기무국  주꾸미볶음  부추전  시금치나물  ...   
4     쌀밥 잡곡밥 (쌀,현미흑미:국내산) 떡국  돈육씨앗강정 (돼지고기:국내산) 우엉잡채...   
...                                                 ...   
1200  쌀밥 흑미밥 찰현미밥 아욱국 수제함박스테이크 견과류마카로니범벅 생깻잎지 단호박물김치...   
1201  쌀밥 수수밥 찰현미밥 냉이된장국 동파육 봄동전 청경채 버섯숙회*초장 무생채 양상추샐...   
1202  전주비빔밥*약고추장 계란파국 요거닭 올방개묵무침 파프리카해초무침 포기김치 양상추샐러...   
1203  쌀밥 흑미밥 찰현미밥 전주식콩나물해장국 돈육간장불고기 깐풍연근 연두부*달래양념장 봄...   
1204  쌀밥 귀리밥 찰현미밥 들깨미역국 교촌간장치킨 옥수수콘치즈구이 가지고추장무침 포기김치...   

                                                 dinner   lun_n  din_n  
0     쌀밥 잡곡밥 (쌀,현미흑미:국내산) 육개장  자반고등어구이  두부조림  건파래무침 ...  1039.0  331.0  
1     콩나물밥*양념장 (쌀,현미흑미:국내산) 어묵국  유산슬 (쇠고기:호주산) 아삭고추무...   867.0  560.0  
2     쌀밥 잡곡밥 (쌀,현미흑미:국내산) 청국장찌개  황태양념구이 (황태:러시아산) 고기...  1017.0  573.0  
3     미니김밥*겨자장 (쌀,현미흑미:국내산) 우동  멕시칸샐러드  군고구마  무피클  포...   978.0  525.0  
4     쌀밥 잡곡밥 (쌀,현미흑미:국내산) 차돌박이찌개 (쇠고기:호주산) 닭갈비 (닭고기:...   925.0  330.0  
...                                                 ...     ...    ...  
1200     김치볶음밥 미니쫄우동*맛살튀김 브로콜리깨소스무침 계란후라이 고들빼기무침 겉절이김치   1093.0  421.0  
1201            흑미밥 쇠고기무국 삼치양념구이 비엔나채소볶음 숙주나물당근무침 포기김치    832.0  353.0  
1202        흑미밥 수제비국 수제맛쵸킹탕수육 유부채소겨자냉채 참나물무침 갓김치 겉절이김치    579.0  217.0  
1203            흑미밥 열무된장국 장어강정*데리야끼소스 깻잎쌈*생강채 오이선 포기김치   1145.0  502.0  
1204         (New)할라피뇨멸치주먹밥 잔치국수 수제고기육전 쑥갓나물 양파초절임 깍두기   1015.0  480.0  

[1205 rows x 12 columns]

In [168]:
import time
start = time.time()
.aplly(lambda x : x sum([text.split('/') for text in x.split()], []))




end =time.time()
end - start

AttributeError: 'Series' object has no attribute 'split'

In [38]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

print(arr1[np.newaxis] * arr2)
# print(arr1[:, np.newaxis] * arr2)
# print("\n")
# print(arr1[np.newaxis] + arr2)
# print(arr1[:, np.newaxis] + arr2)

[[1 4 9]]


In [45]:
arr1

array([1, 2, 3])

In [44]:
arr1[np.newaxis]

array([[1, 2, 3]])

In [46]:
arr1*arr2

array([1, 4, 9])

In [47]:
arr1[:, np.newaxis]

array([[1],
       [2],
       [3]])