In [16]:
from collections import Counter

In [17]:
a=!ls

In [18]:
a

['Untitled.ipynb', 'sample_submission.csv', 'test.csv', 'train.csv']

In [19]:
test=pd.read_csv(a[2])
train=pd.read_csv(a[3])

In [20]:
train.columns=['date', 'day', 'total', 'vacation', 'away', 'extra', 'home', 'morning', 'lunch', 'dinner', 'lun_n', 'din_n']
train.head()

date day  total  vacation  away  extra  home  \
0  2016-02-01   월   2601        50   150    238   0.0   
1  2016-02-02   화   2601        50   173    319   0.0   
2  2016-02-03   수   2601        56   180    111   0.0   
3  2016-02-04   목   2601       104   220    355   0.0   
4  2016-02-05   금   2601       278   181     34   0.0   

                                             morning  \
0  모닝롤/찐빵  우유/두유/주스 계란후라이  호두죽/쌀밥 (쌀:국내산) 된장찌개  쥐...   
1  모닝롤/단호박샌드  우유/두유/주스 계란후라이  팥죽/쌀밥 (쌀:국내산) 호박젓국찌...   
2  모닝롤/베이글  우유/두유/주스 계란후라이  표고버섯죽/쌀밥 (쌀:국내산) 콩나물국...   
3  모닝롤/토마토샌드  우유/두유/주스 계란후라이  닭죽/쌀밥 (쌀,닭:국내산) 근대국...   
4  모닝롤/와플  우유/두유/주스 계란후라이  쇠고기죽/쌀밥 (쌀:국내산) 재첩국  방...   

                                               lunch  \
0  쌀밥/잡곡밥 (쌀,현미흑미:국내산) 오징어찌개  쇠불고기 (쇠고기:호주산) 계란찜 ...   
1  쌀밥/잡곡밥 (쌀,현미흑미:국내산) 김치찌개  가자미튀김  모둠소세지구이  마늘쫑무...   
2  카레덮밥 (쌀,현미흑미:국내산) 팽이장국  치킨핑거 (닭고기:국내산) 쫄면야채무침 ...   
3  쌀밥/잡곡밥 (쌀,현미흑미:국내산) 쇠고기무국  주꾸미볶음  부추전  시금치나물  ...   
4  쌀밥/잡곡밥 (쌀,현미흑미:국내산) 떡국  돈육씨앗강정 (돼지고기:국내산) 우엉잡채...   

                                              dinner   lun_n  din_n  
0  쌀밥/잡곡밥 (쌀,현미흑미:국내산) 육개장  자반고등어구이  두부조림  건파래무침 ...  1039.0  331.0  
1  콩나물밥*양념장 (쌀,현미흑미:국내산) 어묵국  유산슬 (쇠고기:호주산) 아삭고추무...   867.0  560.0  
2  쌀밥/잡곡밥 (쌀,현미흑미:국내산) 청국장찌개  황태양념구이 (황태:러시아산) 고기...  1017.0  573.0  
3  미니김밥*겨자장 (쌀,현미흑미:국내산) 우동  멕시칸샐러드  군고구마  무피클  포...   978.0  525.0  
4  쌀밥/잡곡밥 (쌀,현미흑미:국내산) 차돌박이찌개 (쇠고기:호주산) 닭갈비 (닭고기:...   925.0  330.0

In [83]:
menu_m=tuple(np.squeeze(train['morning'], axis=0))

In [84]:
def split_(x):
    x.split()
    return x

In [85]:
list(map(split_,menu_m))

['모닝롤/찐빵  우유/두유/주스 계란후라이  호두죽/쌀밥 (쌀:국내산) 된장찌개  쥐어채무침  포기김치 (배추,고추가루:국내산) ',
 '모닝롤/단호박샌드  우유/두유/주스 계란후라이  팥죽/쌀밥 (쌀:국내산) 호박젓국찌개  시래기조림  포기김치 (배추,고추가루:국내산) ',
 '모닝롤/베이글  우유/두유/주스 계란후라이  표고버섯죽/쌀밥 (쌀:국내산) 콩나물국  느타리호박볶음  포기김치 (배추,고추가루:국내산) ',
 '모닝롤/토마토샌드  우유/두유/주스 계란후라이  닭죽/쌀밥 (쌀,닭:국내산) 근대국  멸치볶음  포기김치 (배추,고추가루:국내산) ',
 '모닝롤/와플  우유/두유/주스 계란후라이  쇠고기죽/쌀밥 (쌀:국내산) 재첩국  방풍나물  포기김치 (배추,고추가루:국내산) ',
 '팬케익/찐빵  우유/두유/주스  계란후라이  견과류죽/쌀밥 (쌀:국내산) 감자찌개  명엽채무침 포기김치 (김치:국내산) ',
 '모닝롤/야채샌드  우유/두유/주스  계란후라이  고구마죽/쌀밥 (쌀:국내산) 봄동된장국  숙주나물 포기김치 (김치:국내산) ',
 '모닝롤/치즈프레즐  우유/두유/주스  계란후라이  잣죽/쌀밥 (쌀:국내산) 민물새우찌개  콩조림 포기김치 (김치:국내산) ',
 '모닝롤/마늘빵  우유/두유/주스  계란후라이  단호박죽/쌀밥 (쌀:국내산) 어묵국  김구이 포기김치 (김치:국내산) ',
 '모닝롤/참치샌드  우유/두유/주스  계란후라이  흑임자죽/쌀밥 (쌀:국내산) 북어계란국  무생채 포기김치 (김치:국내산) ',
 '모닝롤/인절미토스트  우유/두유/주스  계란후라이  계란후라이  (쌀:국내산) 선지해장국 (쇠고기:호주산) 톳두부무침 포기김치 (김치:국내산) ',
 '모닝롤/씨크립샌드  우유/두유/주스  계란후라이  밤죽/쌀밥 (쌀:국내산) 홍합탕  오이생채 포기김치 (김치:국내산) ',
 '모닝롤/팬케익  우유/주스  계란후라이  브로컬리죽/쌀밥 (쌀:국내산) 고추장찌개  시금치나물 포기김치 (고춧가루:국내산) ',
 '모닝롤/야채샌드  우유/주스 

In [24]:
x=['1','1','1','2']
Counter(x)

Counter({'1': 3, '2': 1})

In [26]:
dict(Counter(x))

{'1': 3, '2': 1}

In [ ]:
train()

In [38]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

print(arr1[np.newaxis] * arr2)
# print(arr1[:, np.newaxis] * arr2)
# print("\n")
# print(arr1[np.newaxis] + arr2)
# print(arr1[:, np.newaxis] + arr2)

[[1 4 9]]


In [45]:
arr1

array([1, 2, 3])

In [44]:
arr1[np.newaxis]

array([[1, 2, 3]])

In [46]:
arr1*arr2

array([1, 4, 9])

In [47]:
arr1[:, np.newaxis]

array([[1],
       [2],
       [3]])